/* Generated by build-aot.sh -- do not edit.
   ECL names each module's init function unpredictably, so it is read back out
   of the object file and pinned here. */
#ifndef AOT_INIT_H
#define AOT_INIT_H
extern void __ecl_initlqb27doE9VlxC_JKy1xN81(cl_object);
#define AOT_INIT_FUNCTION __ecl_initlqb27doE9VlxC_JKy1xN81
#endif
