#!/bin/sh
#
# Compile lisp-src/aot.lisp to iOS object files, on the host, ahead of time.
#
# The host ECL's compiler emits C and then invokes a C compiler; pointing that
# compiler at an iOS SDK is all it takes to cross-compile Lisp for the phone.
#
# Products, per platform, under aot/<platform>/:
#   aot.o        the compiled module, linked in via OTHER_LDFLAGS
#   aot-init.h   its module init symbol, which ECL randomises per compile and
#                which therefore has to be read back out of the object

set -e
cd "`dirname "$0"`"

ECL=../ecl-native/bin/ecl
PLATFORMS=`xcode-select --print-path`/Platforms

if [ ! -x "$ECL" ]; then
  echo "host ECL not found -- run ../build.sh first" >&2
  exit 1
fi

compile_for() {
  platform=$1
  sdk=$2
  min_flag=$3
  include=$4

  mkdir -p "aot/$platform"

  "$ECL" -norc \
    -eval '(require :cmp)' \
    -eval '(setf ffi::*use-dffi* nil)' \
    -eval "(setf c::*cc* \"clang\"
                 c::*cc-flags* \"-arch arm64 $min_flag -isysroot $sdk -I`pwd`/$include -fPIC -fno-common -Ddarwin -O2\")" \
    -eval "(multiple-value-bind (out warnings failure)
               (compile-file \"lisp-src/aot.lisp\" :system-p t
                             :output-file \"aot/$platform/aot.o\")
             (declare (ignore out warnings))
             (when failure (ext:quit 1)))" \
    -eval '(ext:quit)' > /dev/null

  # Mach-O prefixes C identifiers with an underscore; strip exactly one.
  symbol=`nm -g "aot/$platform/aot.o" | awk '/ T ___ecl_init/ { print substr($3, 2) }'`
  if [ -z "$symbol" ]; then
    echo "no init symbol in aot/$platform/aot.o" >&2
    exit 1
  fi

  cat > "aot/$platform/aot-init.h" <<HEADER
/* Generated by build-aot.sh -- do not edit.
   ECL names each module's init function unpredictably, so it is read back out
   of the object file and pinned here. */
#ifndef AOT_INIT_H
#define AOT_INIT_H
extern void $symbol(cl_object);
#define AOT_INIT_FUNCTION $symbol
#endif
HEADER

  printf "%-18s %-38s %s\n" "$platform" "$symbol" \
    "`otool -lv aot/$platform/aot.o | grep -E 'platform ' | head -1 | sed 's/^ *//'`"
}

compile_for iphonesimulator \
  "$PLATFORMS/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk" \
  "-mios-simulator-version-min=15.0" ../ecl-iOS-sim/include

compile_for iphoneos \
  "$PLATFORMS/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk" \
  "-miphoneos-version-min=15.0" ../ecl-iOS/include
